-- Script de creacion obtenido de la ejecucion de Springboot - Hibernate --

create table "public"."cheque" (
	"fecha_emision" date,
	"suma" float(53),
	"medio_pago_id" bigint not null,
	"cuit" varchar(255),
	"titular" varchar(255),
	primary key ("medio_pago_id")
)

create table "public"."efectivo" (
	"medio_pago_id" bigint not null,
	"nacionalidad" varchar(255),
	primary key ("medio_pago_id")
)

create table "public"."medio_de_pago" (
	"id" bigint generated by default as identity,
	primary key ("id")
)

create table "public"."tarjeta_de_credito" (
	"vencimiento" date,
	"medio_pago_id" bigint not null,
	"pan" varchar(255),
	"titular" varchar(255),
	primary key ("medio_pago_id")
)

create table "public"."tarjeta_de_debito" (
	"vencimiento" date,
	"medio_pago_id" bigint not null,
	"pan" varchar(255),
	"titular" varchar(255),
	primary key ("medio_pago_id")
)

create table "public"."alojado" (
	"tipo_alojado" varchar(31) not null,
	"tipo_doc" varchar(50) not null check ("tipo_doc" in ('DNI','LE','LC','PASAPORTE','OTRO')),
	"nro_doc" varchar(255) not null,
	"razon_social" varchar(255),
	primary key ("tipo_doc", "nro_doc")
)

create table "public"."alojado_lista_estadias" (
	"lista_estadias_id_estadia" bigint not null,
	"alojado_tipo_doc" varchar(50) not null,
	"alojado_nro_doc" varchar(255) not null
)

create table "public"."alojado_lista_reservas" (
	"lista_reservas_id_reserva" bigint not null,
	"alojado_tipo_doc" varchar(50) not null,
	"alojado_nro_doc" varchar(255) not null
)

create table "public"."check_in" (
	"fecha_hora_in" date,
	"id_check_in" bigint generated by default as identity,
	primary key ("id_check_in")
)

create table "public"."check_in_alojado" (
	"check_ins_id_check_in" bigint not null,
	"alojado_tipo_doc" varchar(50) not null,
	"alojado_nro_doc" varchar(255) not null
)

create table "public"."check_out" (
	"fecha_hora_out" timestamp(6),
	"id_check_out" bigint generated by default as identity,
	primary key ("id_check_out")
)

create table "public"."check_out_alojado" (
	"check_outs_id_check_out" bigint not null,
	"alojado_tipo_doc" varchar(50) not null,
	"alojado_nro_doc" varchar(255) not null
)

create table "public"."datos_alojado" (
	"fechanac" date,
	"tipo_doc" varchar(50) not null check ("tipo_doc" in ('DNI','LE','LC','PASAPORTE','OTRO')),
	"apellido" varchar(255),
	"calle" varchar(255),
	"cod_post" varchar(255),
	"cuit" varchar(255),
	"depto" varchar(255),
	"email" varchar(255),
	"localidad" varchar(255),
	"nacionalidad" varchar(255),
	"nombre" varchar(255),
	"nro_calle" varchar(255),
	"nro_doc" varchar(255) not null,
	"ocupacion" varchar(255),
	"pais" varchar(255),
	"piso" varchar(255),
	"posicion_iva" varchar(255),
	"prov" varchar(255),
	"telefono" varchar(255),
	primary key ("tipo_doc", "nro_doc")
)

create table "public"."estadia" (
	"fecha_fin" date,
	"fecha_inicio" date,
	"datos_check_in_id_check_in" bigint unique,
	"datos_check_out_id_check_out" bigint unique,
	"habitacion_nro_hab" bigint,
	"id_estadia" bigint generated by default as identity,
	"reserva_id_reserva" bigint,
	primary key ("id_estadia")
)

create table "public"."estadia_lista_servicios" (
	"estadia_id_estadia" bigint not null,
	"lista_servicios_id_servicio" bigint not null
)

create table "public"."factura" (
	"fecha_factura" date,
	"importe_iva" float4 not null,
	"importe_neto" float4 not null,
	"importe_total" float4 not null,
	"num_factura" integer not null,
	"tipo_factura" smallint check ("tipo_factura" between 0 and 3),
	"id" bigint generated by default as identity,
	"destinatario" varchar(255),
	primary key ("id")
)

create table "public"."factura_nota_credito" (
	"factura_id" bigint not null,
	"nota_credito_id" bigint not null unique
)

create table "public"."habitacion" (
	"capacidad" integer not null,
	"estado_hab" smallint check ("estado_hab" between 0 and 3),
	"tarifa" float4 not null,
	"tipo_hab" smallint check ("tipo_hab" between 0 and 4),
	"nro_hab" bigint generated by default as identity,
	primary key ("nro_hab")
)

create table "public"."nota_de_credito" (
	"monto_n_credito" float4,
	"id" bigint generated by default as identity,
	"id_factura_id" bigint,
	primary key ("id")
)

create table "public"."pago" (
	"fecha_pago" date,
	"monto" float4 not null,
	"estadia_pago_id_estadia" bigint,
	"factura_id" bigint unique,
	"id" bigint generated by default as identity,
	"medio_pago_id" bigint unique,
	"responsable_pago_cuit" bigint,
	primary key ("id")
)

create table "public"."reserva" (
	"fecha_fin" date,
	"fecha_inicio" date,
	"id_reserva" bigint generated by default as identity,
	"apellido" varchar(255),
	"estado" varchar(255),
	"nombre" varchar(255),
	"telefono" varchar(255),
	primary key ("id_reserva")
)

create table "public"."reserva_lista_habitaciones" (
	"lista_habitaciones_nro_hab" bigint not null,
	"reserva_id_reserva" bigint not null
)

create table "public"."responsable_de_pago" (
	"telefono" integer not null,
	"cuit" bigint not null,
	"calle" varchar(255),
	"cod_post" varchar(255),
	"depto" varchar(255),
	"localidad" varchar(255),
	"nro_calle" varchar(255),
	"pais" varchar(255),
	"piso" varchar(255),
	"prov" varchar(255),
	"razon_social" varchar(255),
	primary key ("cuit")
)

create table "public"."servicio" (
	"tipo_servicio" smallint check ("tipo_servicio" between 0 and 2),
	"id_servicio" bigint generated by default as identity,
	primary key ("id_servicio")
)

create table "public"."usuarios" (
	"permisos" integer not null,
	"id" bigint generated by default as identity,
	"nombre" varchar(60) not null unique,
	"contrasenia" varchar(100) not null,
	primary key ("id")
)

alter table if exists "public"."cheque" 
   add constraint "FKhud8uo5difkuriia3q29mooh0" 
   foreign key ("medio_pago_id") 
   references "public"."medio_de_pago"

alter table if exists "public"."efectivo" 
   add constraint "FKl6aq17p1en9jj1wvaydi706xq" 
   foreign key ("medio_pago_id") 
   references "public"."medio_de_pago"

alter table if exists "public"."tarjeta_de_credito" 
   add constraint "FKn6pmcn381aj58nw9bmer86sk4" 
   foreign key ("medio_pago_id") 
   references "public"."medio_de_pago"

alter table if exists "public"."tarjeta_de_debito" 
   add constraint "FK4sug1e1db8ewa3s80chymgiv0" 
   foreign key ("medio_pago_id") 
   references "public"."medio_de_pago"

alter table if exists "public"."alojado" 
   add constraint "FKg0hmmur6klwms2oev6itcklax" 
   foreign key ("tipo_doc", "nro_doc") 
   references "public"."datos_alojado"

alter table if exists "public"."alojado_lista_estadias" 
   add constraint "FKi7t3e012ikybohiuolj067d9r" 
   foreign key ("lista_estadias_id_estadia") 
   references "public"."estadia"

alter table if exists "public"."alojado_lista_estadias" 
   add constraint "FK2rf6anu1rprvoeq35j5slr8c2" 
   foreign key ("alojado_tipo_doc", "alojado_nro_doc") 
   references "public"."alojado"

alter table if exists "public"."alojado_lista_reservas" 
   add constraint "FKqxalvturuifkqruojjbwehbyy" 
   foreign key ("lista_reservas_id_reserva") 
   references "public"."reserva"

alter table if exists "public"."alojado_lista_reservas" 
   add constraint "FKn1t8xuspsocoq2m94sfndhxby" 
   foreign key ("alojado_tipo_doc", "alojado_nro_doc") 
   references "public"."alojado"

alter table if exists "public"."check_in_alojado" 
   add constraint "FKde5tevp1us17aafq4av7ylk1p" 
   foreign key ("alojado_tipo_doc", "alojado_nro_doc") 
   references "public"."datos_alojado"

alter table if exists "public"."check_in_alojado" 
   add constraint "FKavnxs4s35dshv1ulg2we19c8t" 
   foreign key ("check_ins_id_check_in") 
   references "public"."check_in"

alter table if exists "public"."check_out_alojado" 
   add constraint "FK4b9bkviw7k9emhm7b2du2v2l" 
   foreign key ("alojado_tipo_doc", "alojado_nro_doc") 
   references "public"."datos_alojado"

alter table if exists "public"."check_out_alojado" 
   add constraint "FKervn861xwekfwllptugq0wlsy" 
   foreign key ("check_outs_id_check_out") 
   references "public"."check_out"

alter table if exists "public"."estadia" 
   add constraint "FKdcf8b6t674aifp2b2vtafjp2p" 
   foreign key ("datos_check_in_id_check_in") 
   references "public"."check_in"

alter table if exists "public"."estadia" 
   add constraint "FKlpc6pd7equetns3cwwifc70y9" 
   foreign key ("datos_check_out_id_check_out") 
   references "public"."check_out"

alter table if exists "public"."estadia" 
   add constraint "FKfs3x1yu7mtwhsoq9wt621jom7" 
   foreign key ("habitacion_nro_hab") 
   references "public"."habitacion"

alter table if exists "public"."estadia" 
   add constraint "FKfj6j0woi530pb2s0tgdonapxt" 
   foreign key ("reserva_id_reserva") 
   references "public"."reserva"

alter table if exists "public"."estadia_lista_servicios" 
   add constraint "FKqrgrk3cxrp1dgfjdis2r2jbpk" 
   foreign key ("lista_servicios_id_servicio") 
   references "public"."servicio"

alter table if exists "public"."estadia_lista_servicios" 
   add constraint "FKppfq03taik5xj3rpof0e9m6xh" 
   foreign key ("estadia_id_estadia") 
   references "public"."estadia"

alter table if exists "public"."factura_nota_credito" 
   add constraint "FK9qla31t47lnrmb7ff81ksntqd" 
   foreign key ("nota_credito_id") 
   references "public"."nota_de_credito"

alter table if exists "public"."factura_nota_credito" 
   add constraint "FK24eg9nep001g0lh26v6nmncw" 
   foreign key ("factura_id") 
   references "public"."factura"

alter table if exists "public"."nota_de_credito" 
   add constraint "FKaeu333oky61o9vshov7bi24q8" 
   foreign key ("id_factura_id") 
   references "public"."factura"

alter table if exists "public"."pago" 
   add constraint "FK4h9sg5mptljfm4k9hun8immf4" 
   foreign key ("estadia_pago_id_estadia") 
   references "public"."estadia"

alter table if exists "public"."pago" 
   add constraint "FKm8ci8fuijqcrw94km6qd3a3q0" 
   foreign key ("factura_id") 
   references "public"."factura"

alter table if exists "public"."pago" 
   add constraint "FK9xlwf60i2nmegl4p20ar9g0y8" 
   foreign key ("medio_pago_id") 
   references "public"."medio_de_pago"

alter table if exists "public"."pago" 
   add constraint "FK4nafjpkruo1luijcdsvr6iuo4" 
   foreign key ("responsable_pago_cuit") 
   references "public"."responsable_de_pago"

alter table if exists "public"."reserva_lista_habitaciones" 
   add constraint "FK9064ldytwrag25tmewhpjgeoq" 
   foreign key ("lista_habitaciones_nro_hab") 
   references "public"."habitacion"

alter table if exists "public"."reserva_lista_habitaciones" 
   add constraint "FK2e3ul1nhcft9fopksiksx9g9g" 
   foreign key ("reserva_id_reserva") 
   references "public"."reserva"
